export const displayHomeAssets = {
  brand: {
    logo: '/display/reference/brand/logo.svg',
    appDownload: '/display/reference/brand/APP_download.png',
    announce: '/display/reference/brand/announce.png',
    news: '/display/reference/brand/news.png',
    navArrowWhite: '/display/reference/brand/cpdt_white.png',
    navArrowRed: '/display/reference/brand/cpdt_red.png',
  },
  quickCards: {
    jisusc: '/display/reference/lottery/video-jisusc.jpg',
    jisuft: '/display/reference/lottery/video-jsft.jpg',
    xingyft: '/display/reference/lottery/video-xingyft.jpg',
    aozxy10: '/display/reference/lottery/video-azxy10.jpg',
    xyssc: '/display/reference/lottery/video-xyssc.jpg',
  },
  lotteryLogos: {
    jisusc: '/display/reference/lottery/jisusc.png',
    jisuft: '/display/reference/lottery/jisuft.png',
    jisussc: '/display/reference/lottery/jisussc.png',
    sgAirship: '/display/reference/lottery/sgAirship.png',
    sg11x5: '/display/reference/lottery/sg11x5.png',
    aozxy5: '/display/reference/lottery/aozxy5.png',
    aozxy10: '/display/reference/lottery/aozxy10.png',
    kuai3Sg: '/display/reference/lottery/Kuai3_sg.png',
  },
  recommendations: {
    happy28: '/display/reference/lottery/recommend-happy28.jpg',
    bingo: '/display/reference/lottery/recommend-bingo.jpg',
    jisuSaiche: '/display/reference/lottery/recommend-jisu-saiche.png',
    sscJisu: '/display/reference/lottery/recommend-ssc-jisu.png',
    sportJsydh: '/display/reference/lottery/recommend-sport-jsydh.png',
    sportKlydh: '/display/reference/lottery/recommend-sport-klydh.png',
    hksmSix: '/display/reference/lottery/recommend-hksmsixlogo.png',
    sgssc: '/display/reference/lottery/recommend-sgssc.png',
    sgAirship: '/display/reference/lottery/recommend-sgAirship.png',
    pcdd: '/display/reference/lottery/recommend-pcdd.png',
  },
  promos: {
    pk10: '/display/reference/promo/pk10.png',
    ssc: '/display/reference/promo/ssc.png',
    eleven: '/display/reference/promo/11check5.png',
    k3: '/display/reference/promo/k3.png',
    pcdd: '/display/reference/promo/pcdd.png',
  },
} as const
