CREATE TABLE avatar_preset (
    avatar_key VARCHAR(64) NOT NULL,
    display_order INT NOT NULL,
    assigned_user_id BIGINT NULL,
    assigned_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (avatar_key),
    CONSTRAINT uk_avatar_preset_order UNIQUE (display_order),
    CONSTRAINT uk_avatar_preset_assignee UNIQUE (assigned_user_id),
    CONSTRAINT fk_avatar_preset_user FOREIGN KEY (assigned_user_id) REFERENCES sys_user(id) ON DELETE SET NULL
);

INSERT INTO avatar_preset (avatar_key, display_order) VALUES
    ('preset-01.jpg', 1),
    ('preset-02.jpg', 2),
    ('preset-03.jpg', 3),
    ('preset-04.jpg', 4),
    ('preset-05.jpg', 5),
    ('preset-06.jpg', 6),
    ('preset-07.jpg', 7),
    ('preset-08.jpg', 8),
    ('preset-09.png', 9),
    ('preset-10.jpg', 10),
    ('preset-11.jpg', 11),
    ('preset-12.jpg', 12),
    ('preset-13.png', 13),
    ('preset-14.png', 14),
    ('preset-15.png', 15),
    ('preset-16.jpg', 16),
    ('preset-17.jpg', 17),
    ('preset-18.jpg', 18),
    ('preset-19.jpg', 19),
    ('preset-20.jpg', 20),
    ('preset-21.jpg', 21),
    ('preset-22.jpg', 22),
    ('preset-23.jpg', 23),
    ('preset-24.jpg', 24),
    ('preset-25.jpg', 25),
    ('preset-26.jpg', 26),
    ('preset-27.jpg', 27),
    ('preset-28.jpg', 28),
    ('preset-29.jpg', 29),
    ('preset-30.jpg', 30),
    ('preset-31.jpg', 31),
    ('preset-32.jpg', 32),
    ('preset-33.jpg', 33),
    ('preset-34.jpg', 34),
    ('preset-35.jpg', 35),
    ('preset-36.jpg', 36),
    ('preset-37.jpg', 37),
    ('preset-38.jpg', 38),
    ('preset-39.jpg', 39),
    ('preset-40.jpg', 40);
